language: java

jdk:
  - openjdk11
  
sudo: required

install: true

before_install:
  - echo "before_install  ---> Dando permissão de exec pra o mvnw e scripts .sh ---> "
  - sudo chmod +x mvnw ./deployment/*

script:
  - echo "Iniciando Fase d _script ---> Build e testes da aplicação ---> "
  - BUILD_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
  - echo "Versão da API - ${BUILD_VERSION}" 
#  - ./mvnw dependency:purge-local-repository clean install
#  - ./mvnw install -DskipTests
  - ./mvnw package  -DskipTests
 
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: desafio-petz-api
  skip_cleanup: true
  on:
    repo: tperrut/petz-api

    
addons:
  sonarcloud:
    organization: tperrut
    token:
      secure: $SONAR_API_KEY

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'  

git:
  depth: false
  
