language: java

services:
  - docker
      
jdk:
  - openjdk11
  
sudo: required

install: true

before_install:
  - echo "before_install  ---> "
  - echo "login no docker ---> "
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 
  - echo "Docker pull da imagem ---> "
  - docker pull tperrut/petz-api:0.0.4-SNAPSHOT
 
  - echo "Dando permissão de exec pra o mvnw e scripts .sh ---> "
  - sudo chmod +x mvnw ./deployment/*
   
script:
  - echo "Iniciando Fase d _script ---> "
  - echo "Build e testes da aplicação ---> "
  - ./mvnw clean package install -DskipTests=true
  - ./deployment/run-tests.sh
 
  - ./mvnw clean package -Pprod
  
  - echo "Deployanduuuuuu no Heroku ======================--> "
  - ./mvnw heroku:deploy jib:build -P deploy-heroku,deploy-docker 
addons:
  sonarcloud:
    organization: tperrut
    token:
      secure: $SONAR_API_KEY


cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'  

git:
  depth: false
  
