language: java

script:
  - ./deployment/run-tests.sh

jdk:
  - openjdk8

before_install:
  - chmod +x mvnw
  - chmod +x ./deployment/run-tests.sh

before_deploy:
  - ./mvnw package -P prod -DskipTests=true
deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: desafio-petz-api
  on:
    repo: tperrut/petz-api
 

