language: java

services:
  - docker
      
jdk:
  - openjdk11
  
sudo: required

install: true

before_install:
  - echo "before_install  ---> "
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_API_KEY" | docker login -u "$HEROKU_LOGIN" --password-stdin registry.heroku.com  
 
  - echo "Dando permissão de exec pra o mvnw e scripts .sh ---> "
  - sudo chmod +x mvnw ./deployment/*

script:
  - echo "Iniciando Fase d _script ---> Build e testes da aplicação ---> "
  - BUILD_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
  - echo $BUILD_VERSION
  
  - export TAG_IMAGE_NAME=${LOGIN_DEFAULT}/${APP_NAME}:${BUILD_VERSION}
  - export TAG_IMAGE_HEROKU_NAME=${HEROKU_APP}/${APP_NAME}:${BUILD_VERSION}
  - echo ${TAG_IMAGE_NAME} - ${TAG_IMAGE_HEROKU_NAME}  
    
  - ./mvnw clean package install -DskipTests=true
  - ./deployment/run-tests.sh
 
  # build docker images
  - ./mvnw clean package -Pprod -DskipTests=true
  - docker build -t ${TAG_IMAGE_NAME} .
  - docker build -t ${TAG_IMAGE_HEROKU} .
  
  - docker build -t registry.heroku.com/${HEROKU_APP}/web .
  - docker tag ${TAG_IMAGE_HEROKU_NAME} registry.heroku.com/${HEROKU_APP}/web
  
#  - echo "Deployanduuuuuu no Heroku ======================--> "
#  - ./mvnw heroku:deploy jib:build -P deploy-heroku,deploy-docker 

deploy:
  provider: script
  script: 
    # push to dockerhub & heroku
    docker push ${TAG_IMAGE_HEROKU_NAME};
    docker push registry.heroku.com/${HEROKU_APP}/web;
    
    
  on:
    branch: feature/add-docker
    
addons:
  sonarcloud:
    organization: tperrut
    token:
      secure: $SONAR_API_KEY


cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'  

git:
  depth: false
  
