language: java

script: 
  - ./mvnw clean install
  - ./mvnw help:active-profiles
  - ./deployment/build-test.sh
  
jdk:
  - openjdk8

before_install:
  - chmod +x mvnw
  - chmod +x ./deployment/run-tests.sh

deploy:
  provider: heroku
  api_key:
    secure: "${HEROKU_API_KEY}"