language: java

install: true

script:
  - ./deployment/run-tests.sh
addons:
  sonarcloud:
    organization: tperrut
    token:
      secure: "DFz4PhKABNr6+ULxecMep7LKxULNBf60/dUOV0gjlsL7tBwRuQz1xYurVzg8yVbk/c8VE6ASRBrx8a6u4AEadfDMxoC+djHUZsKA8dkTnodWA+ke8ULdCVi9Kyba5SxmRDAtvnd/BtnFgaGyNSd3V85eoAUCX22wD+vKUG98WyQtQV9cE/g2oHFryGJtqWBBbYTNq6BYMsft4IHEPI78MiDkluVKpd7UZU8cEGXjWiLTHTZgjHoW2l9U9OAOT9FLP2GhYzgeZk4Gn4tlZH5Adg32mIWxOXX1+PgqmQQQoDqE0MEh600IqpjGukhAhfCqVjB/U/kW4fpP36hc4F2hW9B7ybmBw6mKjDX5n5SYP9Q3i4cWg9mQnlZFJzlz/OtNcT78JSufXqAYUidPZRYqKlexM+LInA0cgDqQ3U189FqO8RGoxa44QD/NgQ30Myzv4LOJVojgURkrNI/xUSmW3Q5iwJD5mJFL1AiWP5Bq3kHfgu7oTxkJpTknHbbKkq3zrtHPTLvylwqw+OLqobAeiA2cRL8XCmjq0pD+wDFNo001Szb4/wNgdgaVRzekJ4HLh/s1kmMo/8bhsu2ZFJ7bUK1gvHNtM/5+NCVS5+0GOB3sPtrO5aGemKFmCOwTO4ZSAQfHUaQRY8K1dNft8CjV9PHY3zHZ0z+3nDehDZ9c8M0="
jdk:
- openjdk8

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'  

before_install:
  - chmod +x mvnw
  - chmod +x ./deployment/run-tests.sh
  - mkdir logs

before_deploy:
  - ./mvnw package -P prod -DskipTests=true

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: desafio-petz-api
  on:
    repo: tperrut/petz-api

env:
  global:
    secure: "x73NFEAmnm4P5bkJVTaKrHGiOu3+Z8UEsPB/4qgksHuDADAMFFPWv2Awjp5KkH+GfINMZ6qYIVyJL2Fi8qpDXFfgqcmVn1o35HOkYJA+j3QbGHzr6cChZ5lmxiBuEoRa18/eyx4VVbXQIAciNX5MVyT0f/Jw04zUvd1BhXjLl/oU/5XGrtukFLvEJC+6WanwG/gj1FGrNmuRBJ3ccRrvGqYEUOEQHajgL99NC+eXN4OoNGALiyxw1x8VSIOTwa7bwfhkSDaxiC5va7mIB7zFquY0fBQgrsy7STuMJFhz205PblO2mqxvJUxUCrSJ2fbTM5aRZwI0gKwYaKcoNX/rb++5V9u5awADcPi29Hh+gj2CRnDySu83qeOCi6c25c3YcfNDaK8c2e/FbbcGO1G9JMdjefoxobH9RWB8p1VsyaiXQZcoHOKEKBUemS4MxL5QblhVtkIoOJLqG1HudSQBSWK4MWE4wr9X/jCQYZTO/eoU6NsCOtp4oGgqSPMoQeRjxE9PbjOL/q45YA8tSF9/9UpaDBYbvufSgqxJNqKG0a3iAaI/3CVGzvK3sZANhCtHr2Ntr+rHVfWN7ZkL8wtIFDFGNJs2m+SyOLFNRL4tLPtJfMjzLCg7sSqMNz6422UaHVj165B/ng/Q133K6Ybj4DuspLbAN2HKVlcTt4VHC60="