language: java

script: 
  - ./mvnw clean install
  - ./mvnw help:active-profiles
  - ./mvnw compile -D skipTests=false env=test 
  - ./deployment/run-tests.sh
  
jdk:
  - openjdk8

before_install:
  - chmod +x mvnw
  - chmod +x ./deployment/run-tests.sh

before_deploy: 
  - ./mvnw package -D env=prod

deploy:
  provider: heroku
  api_key:
    secure: "${HEROKU_API_KEY}"