language: java

install: true

script:
  - ./deployment/run-tests.sh
addons:
  sonarcloud:
    organization: tperrut
    token:
      secure: $SONAR_API_KEY
jdk:
- openjdk11

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'  

before_install:
  - chmod +x mvnw
  - chmod +x ./deployment/run-tests.sh
  - mkdir logs

before_deploy:
  - ./mvnw package -P prod -DskipTests=true

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: desafio-petz-api
  on:
    repo: tperrut/petz-api

