language: java

sudo: required

install: true

before_scrip:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin   #login to dockerhub
  - curl https://cli-assets.heroku.com/install.sh | sh  #install heroku
  - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com  #login to registry.heroku.com 
  
script:
  - ./deployment/run-tests.sh
  - docker image ls;
  - docker build -t tperrut/petz-api .
  - docker image ls;
  - docker tag petz-api registry.heroku.com/$HEROKU_APP/web 
 
addons:
  sonarcloud:
    organization: tperrut
    token:
      secure: $SONAR_API_KEY

services:
  - docker
      
jdk:
- openjdk11

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'  

before_install:
  - echo "DOCKER_PASSWORD  ---> "
  - echo "DOCKER_USERNAME  ---> "
  - echo $DOCKER_USERNAME
  
  - chmod +x mvnw ./deployment/*
  - ./mvnw clean package -DskipTests=true
  
before_deploy:
  - ./mvnw package -P prod -DskipTests=true


deploy:   
  provider: script
  script: 
    echo 'HEROKU_APP'
    echo '$HEROKU_APP'  
    docker push tperrut/petz-api;
    docker push registry.heroku.com/$HEROKU_APP/web;
    heroku container:release web --app $HEROKU_APP
  on:
    branch: feature/add-docker

git:
  depth: false
  
