language: java

install: true

script:
  - ./deployment/run-tests.sh
  
addons:
  sonarcloud:
    organization: tperrut
    token:
      secure: $SONAR_API_KEY

services:
  - docker
      
jdk:
- openjdk11

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'  

before_install:
  - ./deployment/init-config.sh 
  - docker pull tperrut/petz-api
  - docker run -d -p 8080:8080 tperrut/petz-api 
  
 
before_deploy:
  - ./mvnw package -P prod -DskipTests=true

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: desafio-petz-api
  skip_cleanup: true
  on:
    repo: tperrut/petz-api

git:
  depth: false
